Remove old project.itemis nexus dependency
mbeddr/mps-gradle-plugin pull request #134
Opened 2022-09-12 08:22 UTC by arimer

This PR removes the dependency to our old NEXUS and switches to the new one: _artifacts.itemis.cloud_
Under this scope some minor version updates were done to match existing artifact version on the new nexus.

- JDK/JBR version updated to 11_0_10-b1341.41 in tests
- Updated MPS version to 2020.3.6 in build and tests
- Removed snapshot publication

2022-09-13 07:45 UTC, arimer commented
After looking at all the different feature branches `v1.x`, `mps/20203`, `mps/20211` I am no longer sure to which target branch my PR should go. 
I'd appriciate any explanation.

2022-09-13 15:46 UTC, wsafonov requested changes
In generall looks good, just minor stuff: 
- we update here to the 2020.3.6 MPS version, which was packaged with the JBR version `11_0_10-b1145.96`. We should probably stick to this version to stay in sync with the JBR version used in MPS
- we can now remove the old nexus repo from publishing repos in this PR as well, as the old nexus anyway gets freezed in couple of days

2022-09-13 16:10 UTC, wsafonov commented
> After looking at all the different feature branches `v1.x`, `mps/20203`, `mps/20211` I am no longer sure to which target branch my PR should go. I'd appriciate any explanation.

I'm also confused by the current branch scheme. The old branching scheme sticked to MPS versions, but then there was an effort by Sergej to refactor this to use semantic versions in https://github.com/mbeddr/mps-build-backends. But the branch `v1.x` introduces schemantic versioning in this repo. So now it got kind of messy here with mixing up different schemes. Probably @sergej-koscejev is the best to provide more information on this.

This also now concerns my comment above on JBR version for MPS 2020.3.6 update, as there is now a separate branch `mps20203` for MPS 2020.3.x which should include that change and not `master`. But I'm not sure about the role of the `master` branch in the new scheme, so we better clarify all this before merging this PR.

2022-09-13 16:16 UTC, sergej-koscejev commented
The only active branches are master and v1.x. I hope that the others are not used but I don't really know.

2022-09-13 17:11 UTC, arimer commented
@wsafonov thx for the review. I missed the relationship between the JBR and the MPS version entirely, nice catch 👍🏼 
In case only `master` and ` v1.x` is active, should we then merge back `mps/20211` into master? Because master is then outdated 🤷🏼

2022-09-14 07:58 UTC, alexanderpann commented
> We should probably stick to this version to stay in sync with the JBR version used in MPS

@wsafonov I am just curious: did we ever have a bug related to using a mismatched JBR version? I can't imagine that a higher JBR version introduces any breaking changes that would affect MPS. The only big change in the past that I can think of is the drop of support for JavaFX. Is there anything else that I am missing?

2022-09-14 13:13 UTC, arimer commented
Updated: 
- we will remove the MPS related changes in this PR
- we will update our downloadJDK tests to match the availale JDK version + distribution types

2022-09-15 09:28 UTC, arimer commented
@wsafonov please have a second look. (I will squash the commits after approval)

2022-09-15 12:45 UTC, wsafonov commented
> > We should probably stick to this version to stay in sync with the JBR version used in MPS
> 
> @wsafonov I am just curious: did we ever have a bug related to using a mismatched JBR version? I can't imagine that a higher JBR version introduces any breaking changes that would affect MPS. The only big change in the past that I can think of is the drop of support for JavaFX. Is there anything else that I am missing?

I'm not aware of serious issues with such incompatibility. It's just to keep the configuration in sync with the corresponding MPS version used on the target branch and to keep everything clean. We would need anyway to clarify the branches scheme and release process for different MPS versions later on.

2022-09-15 12:46 UTC, wsafonov approved these changes

2022-09-15 13:46 UTC, merged